#!/usr/bin/env python3
"""Automated agent demo: runs 15-question session against fastapi/fastapi.

Clones the repo, indexes it, runs each question through CerebrasSession,
tracks compaction events, and generates a full report with ASCII chart.

Usage:
    CEREBRAS_API_KEY=... python3 demo_session.py           # live API
    python3 demo_session.py --mock                         # mock LLM (no API needed)
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

from engine import ChunkLog, CerebrasSession, DecisionRecord, _estimate_tokens

# Re-use agent.py helpers
from agent import index_repo, build_file_tree, format_status, SYSTEM_PROMPT_TEMPLATE


# --- Config ---

REPO_URL = "https://github.com/fastapi/fastapi.git"
REPO_PATH = Path("/tmp/fastapi")
TOKEN_BUDGET = 8192
SOFT_THRESHOLD = 0.7
HARD_THRESHOLD = 0.9

QUESTIONS = [
    "What does this project do?",
    "How is routing implemented?",
    "Where is error handling defined?",
    "How does dependency injection work?",
    "Where are the security utilities?",
    "How does the middleware stack work?",
    "What testing framework is used?",
    "How are WebSocket connections handled?",
    "Go back to routing — how does it handle path parameters?",
    "What about query parameter validation?",
    "How does the OpenAPI schema generation work?",
    "Remember the security utils from earlier — how do they integrate with dependencies?",
    "Where would I add a new middleware?",
    "What was the error handling approach again?",
    "Summarize everything we discussed about routing, security, and error handling",
]

# Turns that test recall of earlier topics (0-indexed)
RECALL_TURNS = {8, 11, 13, 14}

# --- Mock responses (realistic content to exercise engine) ---

MOCK_RESPONSES = [
    # Turn 1: What does this project do?
    """FastAPI is a modern, high-performance web framework for building APIs with Python 3.7+ based on standard Python type hints. It's built on top of Starlette for the web parts and Pydantic for the data parts.

Key features defined in `fastapi/applications.py`:
- Automatic OpenAPI/Swagger documentation generation
- Data validation via Pydantic models
- Dependency injection system
- Async/await support (ASGI)
- Path operations with decorators like `@app.get()`, `@app.post()`

The main entry point is the `FastAPI` class which extends `Starlette`. See `fastapi/__init__.py` for the public API surface. The framework achieves high performance through async request handling and efficient serialization.""",

    # Turn 2: How is routing implemented?
    """Routing in FastAPI is implemented through the `APIRouter` class in `fastapi/routing.py`.

The core routing mechanism:
1. `APIRouter` extends Starlette's `Router` class
2. Route registration uses decorators: `@router.get("/path")`, `@router.post("/path")`, etc.
3. Each route creates an `APIRoute` object that wraps the endpoint function
4. `APIRoute.__init__()` processes path parameters, dependencies, and response models
5. Routes are compiled into a routing table at startup

Path matching uses Starlette's path converters:
- `{item_id}` — string parameter
- `{item_id:int}` — integer parameter
- `{item_id:path}` — path parameter (matches slashes)

The `include_router()` method in `fastapi/applications.py` (line ~180) merges sub-routers with prefix support. Routes are stored in `self.routes` as an ordered list, matched top-to-bottom.""",

    # Turn 3: Where is error handling defined?
    """Error handling in FastAPI is defined across several files:

1. **`fastapi/exception_handlers.py`** — Default exception handlers:
   - `http_exception_handler()` — handles `HTTPException` (returns JSON error response)
   - `request_validation_exception_handler()` — handles `RequestValidationError` from Pydantic

2. **`fastapi/exceptions.py`** — Exception classes:
   - `HTTPException` extends Starlette's `HTTPException` with a `detail` field
   - `RequestValidationError` wraps Pydantic validation errors
   - `WebSocketRequestValidationError` for WebSocket validation failures
   - `FastAPIError` base class for internal framework errors

3. **Custom handlers** via `app.exception_handler(ExcClass)` decorator (in `applications.py`)

4. **Validation errors** are auto-generated by Pydantic when request data doesn't match the declared types. These produce 422 Unprocessable Entity responses with detailed error locations.

The error response format follows RFC 7807 style with `detail` containing error specifics.""",

    # Turn 4: How does dependency injection work?
    """Dependency injection is implemented in `fastapi/dependencies/utils.py` and `fastapi/params.py`.

The DI system works through Python's `Depends()` function:

```python
from fastapi import Depends

async def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/items/")
async def read_items(db: Session = Depends(get_db)):
    ...
```

Key implementation details:
1. `Depends` class in `fastapi/params.py` stores the dependency callable
2. `get_dependant()` in `dependencies/utils.py` recursively resolves the dependency tree
3. Dependencies are resolved at request time via `solve_dependencies()`
4. Generator dependencies (using `yield`) get cleanup via `contextmanager`
5. `use_cache=True` (default) ensures each dependency is called once per request
6. Sub-dependencies are resolved recursively — a dependency can depend on other dependencies

The `Security` class extends `Depends` for OAuth2/API key flows, adding `scopes` support. Dependencies declared at router level apply to all routes in that router.""",

    # Turn 5: Where are the security utilities?
    """Security utilities are in `fastapi/security/` package:

1. **`fastapi/security/oauth2.py`**:
   - `OAuth2PasswordBearer` — extracts Bearer token from Authorization header
   - `OAuth2PasswordRequestForm` — form data for token endpoint
   - `SecurityScopes` — scope checking for role-based access

2. **`fastapi/security/api_key.py`**:
   - `APIKeyHeader` — API key in request header
   - `APIKeyQuery` — API key in query parameter
   - `APIKeyCookie` — API key in cookie

3. **`fastapi/security/http.py`**:
   - `HTTPBasic` — HTTP Basic authentication
   - `HTTPBearer` — HTTP Bearer token
   - `HTTPDigest` — HTTP Digest authentication

4. **`fastapi/security/open_id_connect_url.py`**:
   - `OpenIdConnect` — OpenID Connect discovery

All security classes extend `SecurityBase` and implement `__call__` as async dependency callables. They integrate with the OpenAPI schema to show auth requirements in the docs. The `Security()` function in `fastapi/params.py` wraps these as dependencies with scope support.""",

    # Turn 6: How does the middleware stack work?
    """Middleware in FastAPI follows the ASGI middleware pattern from Starlette.

Implementation in `fastapi/applications.py` and `fastapi/middleware/`:

1. **Adding middleware**:
   ```python
   app.add_middleware(CORSMiddleware, allow_origins=["*"])
   # or via decorator:
   @app.middleware("http")
   async def custom_middleware(request, call_next):
       response = await call_next(request)
       return response
   ```

2. **Middleware stack order** (outermost to innermost):
   - `ServerErrorMiddleware` — catches unhandled exceptions (always first)
   - User-added middleware (in reverse order of `add_middleware` calls)
   - `ExceptionMiddleware` — handles `HTTPException`
   - Router/routes (innermost)

3. **Built-in middleware** in `fastapi/middleware/`:
   - `fastapi/middleware/cors.py` — re-exports Starlette's CORSMiddleware
   - `fastapi/middleware/gzip.py` — GZip compression
   - `fastapi/middleware/httpsredirect.py` — HTTPS redirect
   - `fastapi/middleware/trustedhost.py` — trusted host validation

4. Middleware wraps the ASGI app, processing requests before and responses after the route handler. Each middleware's `__call__` receives `scope, receive, send`.""",

    # Turn 7: What testing framework is used?
    """FastAPI uses **pytest** as its testing framework, with these key components:

1. **Test client**: `from fastapi.testclient import TestClient` (re-exports Starlette's `TestClient` which wraps `httpx`)

2. **Test structure** in `tests/`:
   - `tests/test_tutorial/` — tests for each documentation example
   - `tests/test_applications.py` — core app tests
   - `tests/test_router*.py` — routing tests
   - `tests/test_security*.py` — auth tests

3. **Configuration** in `pyproject.toml`:
   - pytest with async support via `anyio`
   - Coverage via `pytest-cov`

4. **Test pattern**:
   ```python
   from fastapi.testclient import TestClient
   client = TestClient(app)
   response = client.get("/items/1")
   assert response.status_code == 200
   assert response.json() == {"item_id": 1}
   ```

5. **Async testing** uses `@pytest.mark.anyio` for async test functions. The project has extensive test coverage across all features.""",

    # Turn 8: How are WebSocket connections handled?
    """WebSocket handling is implemented in `fastapi/routing.py` via `APIWebSocketRoute` and in `fastapi/websockets.py`.

Key components:
1. **Route registration**:
   ```python
   @app.websocket("/ws")
   async def websocket_endpoint(websocket: WebSocket):
       await websocket.accept()
       while True:
           data = await websocket.receive_text()
           await websocket.send_text(f"Echo: {data}")
   ```

2. **`WebSocket` class** in `fastapi/websockets.py` (extends Starlette's):
   - `accept()` — complete the WebSocket handshake
   - `receive_text()` / `receive_bytes()` / `receive_json()` — receive data
   - `send_text()` / `send_bytes()` / `send_json()` — send data
   - `close()` — close connection with status code

3. **`APIWebSocketRoute`** in `routing.py`:
   - Supports dependency injection (same `Depends()` system)
   - Path parameters work like HTTP routes
   - No response model (streaming protocol)

4. **`WebSocketDisconnect`** exception is raised when client disconnects

5. Dependencies with `yield` are supported for cleanup (e.g., closing DB connections when WS disconnects).""",

    # Turn 9: Go back to routing — how does it handle path parameters?
    """Coming back to routing — path parameters are handled through Starlette's path converters integrated into FastAPI's `APIRoute`.

In `fastapi/routing.py`, path parameters work as follows:

1. **Declaration**: Path parameters are declared in the URL pattern with curly braces:
   ```python
   @app.get("/items/{item_id}")
   async def read_item(item_id: int):  # type annotation drives validation
       return {"item_id": item_id}
   ```

2. **Type conversion** (from Starlette's converters):
   - `{item_id}` → `str` (default)
   - `{item_id:int}` → `int`
   - `{item_id:float}` → `float`
   - `{item_id:path}` → `str` (matches slashes, for file paths)
   - `{item_id:uuid}` → `UUID`

3. **Validation via Pydantic**: FastAPI extends Starlette by using Python type hints:
   - `item_id: int` validates the parameter is an integer
   - `item_id: str = Path(min_length=3)` adds constraints
   - Enum types restrict to allowed values

4. **Resolution in `get_dependant()`** (dependencies/utils.py):
   - Inspects function signature for path parameter names
   - Matches them against URL pattern variables
   - Creates `ModelField` for each with Pydantic validation
   - Invalid values return 422 with error details

5. **Multiple path params**: `"/users/{user_id}/items/{item_id}"` — each resolved independently.""",

    # Turn 10: What about query parameter validation?
    """Query parameter validation in FastAPI uses Pydantic and the `Query()` function from `fastapi/params.py`.

Implementation:

1. **Implicit query params** — any function parameter not in the path is a query param:
   ```python
   @app.get("/items/")
   async def read_items(skip: int = 0, limit: int = 10):
       # GET /items/?skip=5&limit=20
   ```

2. **Explicit validation** with `Query()`:
   ```python
   from fastapi import Query
   @app.get("/items/")
   async def read_items(
       q: str = Query(default=None, min_length=3, max_length=50, regex="^fixedquery$"),
       tags: list[str] = Query(default=[]),
   ):
   ```

3. **`Query` class** in `fastapi/params.py`:
   - Extends `FieldInfo` from Pydantic
   - Supports: `min_length`, `max_length`, `regex`, `gt`, `lt`, `ge`, `le`
   - `alias` for different query param name
   - `deprecated=True` marks in OpenAPI docs

4. **Resolution** in `dependencies/utils.py`:
   - `get_dependant()` identifies query params from function signature
   - Creates Pydantic model fields with validation constraints
   - Invalid values produce 422 responses with field-level error details

5. **List/multi-value**: `tags: list[str] = Query()` handles `?tags=a&tags=b`""",

    # Turn 11: How does the OpenAPI schema generation work?
    """OpenAPI schema generation is implemented in `fastapi/openapi/` package.

Key files and mechanism:

1. **`fastapi/openapi/utils.py`** — `get_openapi()` function:
   - Iterates all registered routes
   - For each `APIRoute`, extracts path, methods, parameters, request body, responses
   - Builds the OpenAPI 3.1.0 JSON schema
   - Called lazily on first access to `/openapi.json`

2. **`fastapi/openapi/models.py`** — Pydantic models for OpenAPI spec:
   - `OpenAPI`, `PathItem`, `Operation`, `Parameter`, `Schema`, etc.
   - These validate the generated schema itself

3. **Schema generation flow**:
   - Route decorators (`@app.get()`) store metadata on the endpoint
   - `APIRoute` extracts: path params, query params, body model, response model
   - Pydantic models → JSON Schema via `model.model_json_schema()`
   - Security schemes from `Security()` dependencies
   - All merged into the final OpenAPI document

4. **Auto-docs endpoints** (in `fastapi/applications.py`):
   - `/docs` — Swagger UI (calls `/openapi.json`)
   - `/redoc` — ReDoc alternative
   - `/openapi.json` — raw schema

5. **Customization**: `app = FastAPI(openapi_tags=[...], openapi_url="/api/v1/openapi.json")`

6. Response models are converted: `response_model=Item` generates the response schema.""",

    # Turn 12: Security + dependency integration
    """Coming back to security utilities and their dependency integration — this is one of FastAPI's most elegant design patterns.

The security classes in `fastapi/security/` are designed as **dependency callables**:

1. **Security as Dependencies**:
   ```python
   from fastapi import Depends, Security
   from fastapi.security import OAuth2PasswordBearer

   oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

   # Used as a dependency — extracts and validates the token
   @app.get("/users/me")
   async def read_users_me(token: str = Depends(oauth2_scheme)):
       user = decode_token(token)
       return user
   ```

2. **`Security()` vs `Depends()`** (in `fastapi/params.py`):
   - `Security(oauth2_scheme, scopes=["read:users"])` adds scope requirements
   - `Depends(oauth2_scheme)` works but doesn't declare scopes in OpenAPI
   - `Security` extends `Depends` with `scopes` and `use_cache` parameters

3. **Chained security dependencies**:
   ```python
   async def get_current_user(token: str = Depends(oauth2_scheme)):
       return decode_jwt(token)

   async def get_current_active_user(user: User = Security(get_current_user, scopes=["active"])):
       if user.disabled:
           raise HTTPException(status_code=400)
       return user
   ```

4. **Integration with OpenAPI** — security dependencies automatically populate:
   - `securitySchemes` in the OpenAPI components
   - Per-operation `security` requirements
   - Scope descriptions in the docs

5. The dependency resolver in `dependencies/utils.py` handles the full chain: extract token → validate → get user → check permissions.""",

    # Turn 13: Where would I add a new middleware?
    """To add new middleware in FastAPI, you have two approaches:

**Approach 1: Function-based middleware** (simplest):
```python
# In your main app file
@app.middleware("http")
async def add_timing_header(request: Request, call_next):
    start = time.time()
    response = await call_next(request)
    response.headers["X-Process-Time"] = str(time.time() - start)
    return response
```

**Approach 2: Class-based ASGI middleware** (reusable):
```python
# Create in a new file, e.g., middleware/timing.py
from starlette.middleware.base import BaseHTTPMiddleware

class TimingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        start = time.time()
        response = await call_next(request)
        response.headers["X-Process-Time"] = str(time.time() - start)
        return response

# Register it:
app.add_middleware(TimingMiddleware)
```

**Where in the codebase**:
- Built-in middleware lives in `fastapi/middleware/`
- Custom middleware should go in your app's `middleware/` directory
- Register in `main.py` or wherever your `FastAPI()` app is created

**Execution order**: Middleware added last executes first (outermost). So:
```python
app.add_middleware(A)  # executes second
app.add_middleware(B)  # executes first (outermost)
```

For pure ASGI middleware (lowest level), implement `__call__(self, scope, receive, send)` directly.""",

    # Turn 14: What was the error handling approach again?
    """Recapping the error handling approach in FastAPI:

1. **Exception classes** (`fastapi/exceptions.py`):
   - `HTTPException` — for HTTP error responses (extends Starlette's with `detail`)
   - `RequestValidationError` — wraps Pydantic validation failures (auto 422)
   - `WebSocketRequestValidationError` — validation errors during WS handshake

2. **Default handlers** (`fastapi/exception_handlers.py`):
   - `http_exception_handler(request, exc)` → JSON `{"detail": exc.detail}`
   - `request_validation_exception_handler(request, exc)` → JSON with error locations

3. **Custom exception handlers**:
   ```python
   @app.exception_handler(StarletteHTTPException)
   async def custom_handler(request, exc):
       return JSONResponse(status_code=exc.status_code, content={"error": exc.detail})
   ```

4. **Validation flow**: Invalid request data → Pydantic raises `ValidationError` → FastAPI catches it → wraps in `RequestValidationError` → returns 422 with field-level errors

5. **Middleware layer**: `ServerErrorMiddleware` (outermost) catches unhandled exceptions → 500 response. `ExceptionMiddleware` handles `HTTPException` → appropriate status code.

6. **Error response format**: `{"detail": [{"loc": ["body", "name"], "msg": "field required", "type": "value_error.missing"}]}` for validation errors.""",

    # Turn 15: Summary
    """Here's a comprehensive summary of routing, security, and error handling in FastAPI:

## Routing
- Implemented via `APIRouter` in `fastapi/routing.py`, extending Starlette's router
- Routes registered with decorators: `@app.get()`, `@app.post()`, etc.
- **Path parameters**: `{param_id}` with type converters (int, float, path, uuid)
- **Query parameters**: implicit from function args not in path; validated via `Query()`
- **Validation**: Pydantic type hints drive automatic validation, producing 422 errors
- Sub-routers merged via `include_router()` with prefix support
- Route matching is ordered, top-to-bottom

## Security
- Security utilities in `fastapi/security/` package
- `OAuth2PasswordBearer`, `APIKeyHeader`, `HTTPBasic`, `HTTPBearer`, `OpenIdConnect`
- All security classes are **dependency callables** — used with `Depends()` or `Security()`
- `Security()` extends `Depends()` with scope support for role-based access
- Chained dependencies: token extraction → user lookup → permission check
- Auto-integrates with OpenAPI schema (securitySchemes, per-operation requirements)
- The dependency injection system (`dependencies/utils.py`) resolves the full auth chain

## Error Handling
- Exception classes in `fastapi/exceptions.py`: `HTTPException`, `RequestValidationError`
- Default handlers in `fastapi/exception_handlers.py` return JSON error responses
- Custom handlers via `@app.exception_handler()` decorator
- Validation errors auto-generated by Pydantic → 422 with field-level details
- Middleware stack: `ServerErrorMiddleware` (500s) → user middleware → `ExceptionMiddleware` (HTTPException)
- Consistent JSON error format with `detail` field

These three systems are deeply integrated: routes declare dependencies (including security), security uses the DI system, and error handling provides consistent error responses across all layers.""",
]


def clone_repo():
    """Clone fastapi if not already present."""
    if REPO_PATH.is_dir() and (REPO_PATH / ".git").is_dir():
        print(f"Repo already exists at {REPO_PATH}")
        return
    print(f"Cloning {REPO_URL} to {REPO_PATH}...")
    subprocess.run(
        ["git", "clone", "--depth", "1", REPO_URL, str(REPO_PATH)],
        check=True,
        capture_output=True,
    )
    print("Clone complete.")


class MockSession:
    """Mock session that returns pre-written responses and appends to ChunkLog."""

    def __init__(self, chunk_log: ChunkLog):
        self.chunk_log = chunk_log
        self._turn_index = 0
        self._ttft_samples: list[float] = []
        self._total_input_tokens = 0
        self._total_output_tokens = 0
        self._total_turns = 0

    @property
    def avg_ttft(self) -> float:
        if not self._ttft_samples:
            return 0.0
        return sum(self._ttft_samples) / len(self._ttft_samples)

    def chat(self, system_prompt: str | None = None) -> str:
        """Return mock response and append to context."""
        idx = min(self._turn_index, len(MOCK_RESPONSES) - 1)
        response = MOCK_RESPONSES[idx]
        self._turn_index += 1

        # Simulate input tokens
        input_tokens = self.chunk_log.current_tokens()
        if system_prompt:
            input_tokens += _estimate_tokens(system_prompt)
        output_tokens = _estimate_tokens(response)

        self._total_input_tokens += input_tokens
        self._total_output_tokens += output_tokens
        self._total_turns += 1
        self._ttft_samples.append(0.05)  # simulate 50ms TTFT

        # Append to context (this triggers compaction)
        self.chunk_log.append("assistant", response, priority=1.0)
        self.chunk_log.next_turn()
        return response

    def get_metrics(self) -> dict:
        return {
            "avg_ttft": round(self.avg_ttft, 4),
            "total_input_tokens": self._total_input_tokens,
            "total_output_tokens": self._total_output_tokens,
            "total_tokens": self._total_input_tokens + self._total_output_tokens,
            "total_turns": self._total_turns,
            "context_size_tokens": self.chunk_log.get_context_tokens(),
            "compaction_events": self.chunk_log.compaction_count,
        }


def run_session(use_mock: bool = False) -> dict:
    """Run the full 15-question session. Returns session data for reporting."""
    api_key = os.environ.get("CEREBRAS_API_KEY")
    if not api_key and not use_mock:
        print("Error: CEREBRAS_API_KEY not set (use --mock for mock mode)")
        sys.exit(1)

    # Initialize engine
    log = ChunkLog(
        db_path=":memory:",
        max_tokens=TOKEN_BUDGET,
        soft_threshold=SOFT_THRESHOLD,
        hard_threshold=HARD_THRESHOLD,
        goal_guided=True,
    )

    if use_mock:
        session = MockSession(log)
        mode_label = "MOCK"
    else:
        session = CerebrasSession(log, api_key=api_key)
        mode_label = "LIVE (Cerebras llama3.1-8b)"

    # Index repo
    print(f"Indexing {REPO_PATH}...")
    file_tree = build_file_tree(REPO_PATH)
    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(
        repo_path=REPO_PATH, file_tree=file_tree,
    )
    sys_tokens = _estimate_tokens(system_prompt)
    print(f"  System prompt: {sys_tokens:,} tokens")

    files = index_repo(REPO_PATH)
    print(f"  Indexing {len(files)} files into context...")
    for f in files:
        content = f"[FILE: {f['path']}]\n{f['content']}"
        log.append("user", content, priority=1.0)

    ctx_after = log.current_tokens()
    chunks_after = log._conn.execute("SELECT COUNT(*) FROM chunks").fetchone()[0]
    print(f"  Context after indexing: {ctx_after:,}/{TOKEN_BUDGET:,} tokens ({chunks_after} chunks)")
    if log.compaction_count > 0:
        evicted = sum(1 for d in log.decisions if d.action.startswith("compact"))
        print(f"  Compaction during indexing: {log.compaction_count} events, {evicted} chunks evicted")

    # Session tracking
    full_log_lines: list[str] = []
    context_sizes: list[int] = [ctx_after]  # size after indexing = turn 0
    turn_data: list[dict] = []
    eviction_log: list[dict] = []

    def log_line(line: str):
        full_log_lines.append(line)
        print(line)

    log_line(f"\n{'='*70}")
    log_line(f"DEMO SESSION — {len(QUESTIONS)} questions against fastapi/fastapi")
    log_line(f"Mode: {mode_label}")
    log_line(f"Budget: {TOKEN_BUDGET:,} tokens | Soft: {SOFT_THRESHOLD} | Hard: {HARD_THRESHOLD}")
    log_line(f"{'='*70}\n")

    for i, question in enumerate(QUESTIONS):
        turn_num = i + 1
        prev_decision_count = len(log.decisions)
        prev_compactions = log.compaction_count

        log_line(f"\n--- Turn {turn_num}/{len(QUESTIONS)} ---")
        log_line(f"Q: {question}")

        # Append user message and advance turn
        log.append("user", question, priority=1.5)
        log.next_turn()

        # Record any compaction from user append
        new_decisions_user = log.decisions[prev_decision_count:]
        user_compactions = [d for d in new_decisions_user if d.action.startswith("compact")]
        for d in user_compactions:
            eviction_log.append({
                "turn": turn_num,
                "phase": "user_append",
                "hash": d.chunk_hash[:16],
                "action": d.action,
                "reason": d.reason,
                "before": d.context_size_before,
                "after": d.context_size_after,
            })
            log_line(f"  [EVICT] {d.action}: {d.chunk_hash[:12]}... ({d.reason}) [{d.context_size_before:,} -> {d.context_size_after:,}]")
        prev_decision_count = len(log.decisions)

        # Call LLM (or mock)
        t0 = time.time()
        try:
            response = session.chat(system_prompt=system_prompt)
            elapsed = time.time() - t0
        except Exception as e:
            response = f"[API Error: {e}]"
            elapsed = time.time() - t0
            # On API error, manually append error as assistant response
            log.append("assistant", response, priority=0.5)
            log.next_turn()

        # Truncate response for display (full version in log file)
        display_response = response[:500] + "..." if len(response) > 500 else response
        log_line(f"A: {display_response}")

        # Record compaction from assistant response
        new_decisions_asst = log.decisions[prev_decision_count:]
        asst_compactions = [d for d in new_decisions_asst if d.action.startswith("compact")]
        for d in asst_compactions:
            eviction_log.append({
                "turn": turn_num,
                "phase": "assistant_append",
                "hash": d.chunk_hash[:16],
                "action": d.action,
                "reason": d.reason,
                "before": d.context_size_before,
                "after": d.context_size_after,
            })
            log_line(f"  [EVICT] {d.action}: {d.chunk_hash[:12]}... ({d.reason}) [{d.context_size_before:,} -> {d.context_size_after:,}]")

        total_compactions_this_turn = (log.compaction_count - prev_compactions)
        evicted_this_turn = len(user_compactions) + len(asst_compactions)

        # Status
        status = format_status(log, session, TOKEN_BUDGET)
        log_line(status)

        ctx_now = log.current_tokens()
        context_sizes.append(ctx_now)

        turn_data.append({
            "turn": turn_num,
            "question": question,
            "response": response,
            "response_len": len(response),
            "elapsed": elapsed,
            "context_tokens": ctx_now,
            "compactions": total_compactions_this_turn,
            "evicted": evicted_this_turn,
            "is_recall": i in RECALL_TURNS,
        })

        # Small delay for live mode
        if not use_mock and i < len(QUESTIONS) - 1:
            time.sleep(1)

    # Final metrics
    metrics = session.get_metrics()
    log_line(f"\n{'='*70}")
    log_line("SESSION COMPLETE")
    log_line(f"{'='*70}")

    log.close()

    return {
        "metrics": metrics,
        "turn_data": turn_data,
        "eviction_log": eviction_log,
        "context_sizes": context_sizes,
        "full_log": full_log_lines,
        "max_tokens": TOKEN_BUDGET,
        "mode": mode_label,
    }


def ascii_chart(values: list[int], max_tokens: int, width: int = 60, height: int = 15) -> str:
    """Render an ASCII chart of context size over turns."""
    if not values:
        return "(no data)"

    max_val = max(max(values), max_tokens)
    lines: list[str] = []

    lines.append(f"Context Size Over Turns (max budget = {max_tokens:,})")
    lines.append("")

    for row in range(height, -1, -1):
        threshold = max_val * row / height
        label = f"{int(threshold):>6} |"
        bar = ""
        for i, v in enumerate(values):
            if v >= threshold:
                bar += "#"
            else:
                bar += " "
        if abs(threshold - max_tokens) < max_val / height / 2:
            bar_with_limit = ""
            for i, v in enumerate(values):
                if v >= threshold:
                    bar_with_limit += "#"
                else:
                    bar_with_limit += "-"
            lines.append(label + bar_with_limit + " <-- budget")
        else:
            lines.append(label + bar)

    lines.append("       +" + "-" * len(values))
    x_labels = "        " + "".join(str(i % 10) for i in range(len(values)))
    lines.append(x_labels)
    lines.append("        " + "^idx   (0=after indexing, 1-15=after each turn)")

    return "\n".join(lines)


def check_recall(turn_data: list[dict]) -> list[dict]:
    """Check whether recall turns reference the expected earlier topics."""
    recall_checks = [
        {
            "turn": 9,
            "topic": "routing + path parameters",
            "keywords": ["path", "param", "route", "routing"],
        },
        {
            "turn": 12,
            "topic": "security + dependency integration",
            "keywords": ["security", "depend", "inject", "oauth", "auth"],
        },
        {
            "turn": 14,
            "topic": "error handling recall",
            "keywords": ["error", "exception", "handler", "handling"],
        },
        {
            "turn": 15,
            "topic": "summary of routing, security, error handling",
            "keywords": ["routing", "security", "error", "route"],
        },
    ]

    results = []
    for check in recall_checks:
        idx = check["turn"] - 1
        if idx >= len(turn_data):
            results.append({**check, "passed": False, "matches": 0, "note": "turn not reached"})
            continue

        response_lower = turn_data[idx]["response"].lower()
        matches = sum(1 for kw in check["keywords"] if kw in response_lower)
        passed = matches >= 2
        results.append({
            **check,
            "passed": passed,
            "matches": matches,
            "total_keywords": len(check["keywords"]),
        })

    return results


def generate_report(data: dict) -> str:
    """Generate the full text report."""
    m = data["metrics"]
    turns = data["turn_data"]
    evictions = data["eviction_log"]
    sizes = data["context_sizes"]

    lines: list[str] = []
    lines.append(f"{'='*70}")
    lines.append(f"DEMO SESSION REPORT — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"{'='*70}")
    lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append(f"  Repository:      fastapi/fastapi")
    lines.append(f"  Mode:            {data['mode']}")
    lines.append(f"  Token budget:    {data['max_tokens']:,}")
    lines.append(f"  Total turns:     {m['total_turns']}")
    lines.append(f"  Total tokens:    {m['total_tokens']:,} ({m['total_input_tokens']:,} in, {m['total_output_tokens']:,} out)")
    lines.append(f"  Avg TTFT:        {m['avg_ttft']:.3f}s")
    lines.append(f"  Compactions:     {m['compaction_events']}")
    lines.append(f"  Final context:   {m['context_size_tokens']:,}/{data['max_tokens']:,} tokens")
    lines.append("")

    # Per-turn summary
    lines.append("## Per-Turn Summary")
    lines.append(f"  {'Turn':>4}  {'Context':>7}  {'Compact':>7}  {'Evicted':>7}  {'Time':>6}  Question")
    lines.append(f"  {'----':>4}  {'-------':>7}  {'-------':>7}  {'-------':>7}  {'----':>6}  {'--------'}")
    for t in turns:
        recall_marker = " [RECALL]" if t["is_recall"] else ""
        lines.append(
            f"  {t['turn']:>4}  {t['context_tokens']:>7,}  {t['compactions']:>7}  {t['evicted']:>7}  {t['elapsed']:>5.1f}s  {t['question'][:50]}{recall_marker}"
        )
    lines.append("")

    # Eviction details
    lines.append("## Eviction Log")
    if evictions:
        lines.append(f"  {'Turn':>4}  {'Phase':>16}  {'Action':>14}  {'Hash':>16}  {'Before':>7} -> {'After':>7}  Reason")
        for e in evictions:
            lines.append(
                f"  {e['turn']:>4}  {e['phase']:>16}  {e['action']:>14}  {e['hash']:>16}  {e['before']:>7,} -> {e['after']:>7,}  {e['reason']}"
            )
    else:
        lines.append("  No evictions occurred.")
    lines.append("")

    # Recall analysis
    lines.append("## Recall Analysis (turns 9, 12, 14, 15)")
    recall_results = check_recall(turns)
    all_passed = True
    for r in recall_results:
        status = "PASS" if r["passed"] else "FAIL"
        if not r["passed"]:
            all_passed = False
        lines.append(
            f"  Turn {r['turn']:>2} ({r['topic']}): {status} "
            f"— {r['matches']}/{r.get('total_keywords', '?')} keywords found"
        )
    lines.append(f"\n  Overall recall: {'ALL PASSED' if all_passed else 'SOME FAILED'}")
    lines.append("")

    # ASCII chart
    lines.append("## Context Size Over Time")
    lines.append(ascii_chart(sizes, data["max_tokens"]))
    lines.append("")

    lines.append(f"{'='*70}")
    lines.append("END OF REPORT")
    lines.append(f"{'='*70}")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Demo session against fastapi/fastapi")
    parser.add_argument("--mock", action="store_true",
                        help="Use mock LLM responses (no API key needed)")
    args = parser.parse_args()

    # Ensure results dir exists
    results_dir = Path("results")
    results_dir.mkdir(exist_ok=True)

    datestamp = datetime.now().strftime("%Y%m%d")

    # Step 1: Clone repo
    clone_repo()

    # Step 2: Run session
    data = run_session(use_mock=args.mock)

    # Step 3: Save full session log
    mode_tag = "mock" if args.mock else "live"
    session_path = results_dir / f"demo_session_{mode_tag}_{datestamp}.txt"
    with open(session_path, "w") as f:
        f.write("\n".join(data["full_log"]))
    print(f"\nSession log saved to {session_path}")

    # Step 4: Generate and save report
    report = generate_report(data)
    report_path = results_dir / f"demo_report_{mode_tag}_{datestamp}.txt"
    with open(report_path, "w") as f:
        f.write(report)
    print(f"Report saved to {report_path}")
    print("\n" + report)


if __name__ == "__main__":
    main()
